package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Assets generated by hbm2java
 */
@Entity
public class Assets implements java.io.Serializable {

    @Id    
    @GeneratedValue(generator="increment")
    @GenericGenerator(name="increment", strategy = "increment")
    private long assetId;
    private SportTypes sportTypes;
    private Assets assets;
    private String vaid;
    private String xaid;
    private Date gameDate;
    private int homeTeamId;
    private int awayTeamId;
    private int filmedByTeamId;
    private long size;
    private String title;
    private String assetFileName;
    private Serializable metaData;
    private boolean availableForDownload;
    private boolean isUploaded;
    private Date assetCreatedDate;
    private Date assetInActiveDate;
    private boolean assetIsActive;
//    private Set assetsSportTeamses = new HashSet(0);
//    private Set assetSportTeamOwnershipLogs = new HashSet(0);

    public Assets() {
    }

    public Assets(SportTypes sportTypes, Assets assets, String vaid, String xaid, Date gameDate, int homeTeamId,
            int awayTeamId, int filmedByTeamId, long size, String title, String assetFileName,
            boolean availableForDownload, boolean isUploaded, Date assetCreatedDate, boolean assetIsActive) {
        this.sportTypes = sportTypes;
        this.assets = assets;
        this.vaid = vaid;
        this.xaid = xaid;
        this.gameDate = gameDate;
        this.homeTeamId = homeTeamId;
        this.awayTeamId = awayTeamId;
        this.filmedByTeamId = filmedByTeamId;
        this.size = size;
        this.title = title;
        this.assetFileName = assetFileName;
        this.availableForDownload = availableForDownload;
        this.isUploaded = isUploaded;
        this.assetCreatedDate = assetCreatedDate;
        this.assetIsActive = assetIsActive;
    }

   
    public long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(long assetId) {
        this.assetId = assetId;
    }

    public SportTypes getSportTypes() {
        return this.sportTypes;
    }

    public void setSportTypes(SportTypes sportTypes) {
        this.sportTypes = sportTypes;
    }

    public String getVaid() {
        return this.vaid;
    }

    public void setVaid(String vaid) {
        this.vaid = vaid;
    }

    public String getXaid() {
        return this.xaid;
    }

    public void setXaid(String xaid) {
        this.xaid = xaid;
    }

    public Date getGameDate() {
        return this.gameDate;
    }

    public void setGameDate(Date gameDate) {
        this.gameDate = gameDate;
    }

    public int getHomeTeamId() {
        return this.homeTeamId;
    }

    public void setHomeTeamId(int homeTeamId) {
        this.homeTeamId = homeTeamId;
    }

    public int getAwayTeamId() {
        return this.awayTeamId;
    }

    public void setAwayTeamId(int awayTeamId) {
        this.awayTeamId = awayTeamId;
    }

    public int getFilmedByTeamId() {
        return this.filmedByTeamId;
    }

    public void setFilmedByTeamId(int filmedByTeamId) {
        this.filmedByTeamId = filmedByTeamId;
    }

    public long getSize() {
        return this.size;
    }

    public void setSize(long size) {
        this.size = size;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAssetFileName() {
        return this.assetFileName;
    }

    public void setAssetFileName(String assetFileName) {
        this.assetFileName = assetFileName;
    }

    public Serializable getMetaData() {
        return this.metaData;
    }

    public void setMetaData(Serializable metaData) {
        this.metaData = metaData;
    }

    public boolean isAvailableForDownload() {
        return this.availableForDownload;
    }

    public void setAvailableForDownload(boolean availableForDownload) {
        this.availableForDownload = availableForDownload;
    }

    public boolean isIsUploaded() {
        return this.isUploaded;
    }

    public void setIsUploaded(boolean isUploaded) {
        this.isUploaded = isUploaded;
    }

    public Date getAssetCreatedDate() {
        return this.assetCreatedDate;
    }

    public void setAssetCreatedDate(Date assetCreatedDate) {
        this.assetCreatedDate = assetCreatedDate;
    }

    public Date getAssetInActiveDate() {
        return this.assetInActiveDate;
    }

    public void setAssetInActiveDate(Date assetInActiveDate) {
        this.assetInActiveDate = assetInActiveDate;
    }

    public boolean isAssetIsActive() {
        return this.assetIsActive;
    }

    public void setAssetIsActive(boolean assetIsActive) {
        this.assetIsActive = assetIsActive;
    }
//
//    public Set getAssetsSportTeamses() {
//        return this.assetsSportTeamses;
//    }
//
//    public void setAssetsSportTeamses(Set assetsSportTeamses) {
//        this.assetsSportTeamses = assetsSportTeamses;
//    }
//
//    public Set getAssetSportTeamOwnershipLogs() {
//        return this.assetSportTeamOwnershipLogs;
//    }
//
//    public void setAssetSportTeamOwnershipLogs(Set assetSportTeamOwnershipLogs) {
//        this.assetSportTeamOwnershipLogs = assetSportTeamOwnershipLogs;
//    }

    public Assets getAssets() {
        return this.assets;
    }

    public void setAssets(Assets assets) {
        this.assets = assets;
    }

}
