package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AssetsSportTeams generated by hbm2java
 */
@Entity
@Table(name = "Assets_SportTeams")
public class AssetsSportTeams implements java.io.Serializable {

    private long assetSportTeamId;
    private Assets assets;
    private SportTeams sportTeams;
    private Users users;
    private Date sharedDate;
    private Serializable usersAllowedAccess;
    private boolean assetSportTeamIsActive;

    public AssetsSportTeams() {
    }

    public AssetsSportTeams(long assetSportTeamId, Assets assets, SportTeams sportTeams, Users users, Date sharedDate,
            boolean assetSportTeamIsActive) {
        this.assetSportTeamId = assetSportTeamId;
        this.assets = assets;
        this.sportTeams = sportTeams;
        this.users = users;
        this.sharedDate = sharedDate;
        this.assetSportTeamIsActive = assetSportTeamIsActive;
    }

    public AssetsSportTeams(long assetSportTeamId, Assets assets, SportTeams sportTeams, Users users, Date sharedDate,
            Serializable usersAllowedAccess, boolean assetSportTeamIsActive) {
        this.assetSportTeamId = assetSportTeamId;
        this.assets = assets;
        this.sportTeams = sportTeams;
        this.users = users;
        this.sharedDate = sharedDate;
        this.usersAllowedAccess = usersAllowedAccess;
        this.assetSportTeamIsActive = assetSportTeamIsActive;
    }

    public long getAssetSportTeamId() {
        return this.assetSportTeamId;
    }

    public void setAssetSportTeamId(long assetSportTeamId) {
        this.assetSportTeamId = assetSportTeamId;
    }

    public Assets getAssets() {
        return this.assets;
    }

    public void setAssets(Assets assets) {
        this.assets = assets;
    }

    public SportTeams getSportTeams() {
        return this.sportTeams;
    }

    public void setSportTeams(SportTeams sportTeams) {
        this.sportTeams = sportTeams;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Date getSharedDate() {
        return this.sharedDate;
    }

    public void setSharedDate(Date sharedDate) {
        this.sharedDate = sharedDate;
    }

    public Serializable getUsersAllowedAccess() {
        return this.usersAllowedAccess;
    }

    public void setUsersAllowedAccess(Serializable usersAllowedAccess) {
        this.usersAllowedAccess = usersAllowedAccess;
    }

    public boolean isAssetSportTeamIsActive() {
        return this.assetSportTeamIsActive;
    }

    public void setAssetSportTeamIsActive(boolean assetSportTeamIsActive) {
        this.assetSportTeamIsActive = assetSportTeamIsActive;
    }

}
