package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DownloadHistory generated by hbm2java
 */
@Entity

public class DownloadHistory implements java.io.Serializable {

    private long downloadHistoryId;
    private int sportTeamId;
    private int userId;
    private long assetId;
    private Date downloadDate;

    public DownloadHistory() {
    }

    public DownloadHistory(long downloadHistoryId, int sportTeamId, int userId, long assetId, Date downloadDate) {
        this.downloadHistoryId = downloadHistoryId;
        this.sportTeamId = sportTeamId;
        this.userId = userId;
        this.assetId = assetId;
        this.downloadDate = downloadDate;
    }

    public long getDownloadHistoryId() {
        return this.downloadHistoryId;
    }

    public void setDownloadHistoryId(long downloadHistoryId) {
        this.downloadHistoryId = downloadHistoryId;
    }

    public int getSportTeamId() {
        return this.sportTeamId;
    }

    public void setSportTeamId(int sportTeamId) {
        this.sportTeamId = sportTeamId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public long getAssetId() {
        return this.assetId;
    }

    public void setAssetId(long assetId) {
        this.assetId = assetId;
    }

    public Date getDownloadDate() {
        return this.downloadDate;
    }

    public void setDownloadDate(Date downloadDate) {
        this.downloadDate = downloadDate;
    }

}
