package com.xosdigital.tcx.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

/**
 * DownloadMetaDataFormatTypes generated by hbm2java
 */
@Entity


public class DownloadMetaDataFormatTypes implements java.io.Serializable {

    private short downloadMetaDataFormatTypeId;
    private String downloadMetaDataFormatName;
    private String downloadMetaDataFormatExtension;
    private boolean downloadMetaDataFormatTypeIsActive;

    public DownloadMetaDataFormatTypes() {
    }

    public DownloadMetaDataFormatTypes(short downloadMetaDataFormatTypeId, String downloadMetaDataFormatName,
            String downloadMetaDataFormatExtension, boolean downloadMetaDataFormatTypeIsActive) {
        this.downloadMetaDataFormatTypeId = downloadMetaDataFormatTypeId;
        this.downloadMetaDataFormatName = downloadMetaDataFormatName;
        this.downloadMetaDataFormatExtension = downloadMetaDataFormatExtension;
        this.downloadMetaDataFormatTypeIsActive = downloadMetaDataFormatTypeIsActive;
    }

    public short getDownloadMetaDataFormatTypeId() {
        return this.downloadMetaDataFormatTypeId;
    }

    public void setDownloadMetaDataFormatTypeId(short downloadMetaDataFormatTypeId) {
        this.downloadMetaDataFormatTypeId = downloadMetaDataFormatTypeId;
    }

    public String getDownloadMetaDataFormatName() {
        return this.downloadMetaDataFormatName;
    }

    public void setDownloadMetaDataFormatName(String downloadMetaDataFormatName) {
        this.downloadMetaDataFormatName = downloadMetaDataFormatName;
    }

    public String getDownloadMetaDataFormatExtension() {
        return this.downloadMetaDataFormatExtension;
    }

    public void setDownloadMetaDataFormatExtension(String downloadMetaDataFormatExtension) {
        this.downloadMetaDataFormatExtension = downloadMetaDataFormatExtension;
    }

    public boolean isDownloadMetaDataFormatTypeIsActive() {
        return this.downloadMetaDataFormatTypeIsActive;
    }

    public void setDownloadMetaDataFormatTypeIsActive(boolean downloadMetaDataFormatTypeIsActive) {
        this.downloadMetaDataFormatTypeIsActive = downloadMetaDataFormatTypeIsActive;
    }

}
