package com.xosdigital.tcx.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

/**
 * DownloadMediaFormatTypes generated by hbm2java
 */

@Entity

public class DownloadMediaFormatTypes implements java.io.Serializable {

    private short downloadMediaFormatTypeId;
    private String sourceMediaFormatName;
    private String downloadMediaFormatName;
    private String downloadMediaFormatExtension;
    private boolean downloadMediaFormatTypeIsActive;

    public DownloadMediaFormatTypes() {
    }

    public DownloadMediaFormatTypes(short downloadMediaFormatTypeId, String sourceMediaFormatName,
            String downloadMediaFormatName, String downloadMediaFormatExtension, boolean downloadMediaFormatTypeIsActive) {
        this.downloadMediaFormatTypeId = downloadMediaFormatTypeId;
        this.sourceMediaFormatName = sourceMediaFormatName;
        this.downloadMediaFormatName = downloadMediaFormatName;
        this.downloadMediaFormatExtension = downloadMediaFormatExtension;
        this.downloadMediaFormatTypeIsActive = downloadMediaFormatTypeIsActive;
    }

    public short getDownloadMediaFormatTypeId() {
        return this.downloadMediaFormatTypeId;
    }

    public void setDownloadMediaFormatTypeId(short downloadMediaFormatTypeId) {
        this.downloadMediaFormatTypeId = downloadMediaFormatTypeId;
    }

    public String getSourceMediaFormatName() {
        return this.sourceMediaFormatName;
    }

    public void setSourceMediaFormatName(String sourceMediaFormatName) {
        this.sourceMediaFormatName = sourceMediaFormatName;
    }

    public String getDownloadMediaFormatName() {
        return this.downloadMediaFormatName;
    }

    public void setDownloadMediaFormatName(String downloadMediaFormatName) {
        this.downloadMediaFormatName = downloadMediaFormatName;
    }

    public String getDownloadMediaFormatExtension() {
        return this.downloadMediaFormatExtension;
    }

    public void setDownloadMediaFormatExtension(String downloadMediaFormatExtension) {
        this.downloadMediaFormatExtension = downloadMediaFormatExtension;
    }

    public boolean isDownloadMediaFormatTypeIsActive() {
        return this.downloadMediaFormatTypeIsActive;
    }

    public void setDownloadMediaFormatTypeIsActive(boolean downloadMediaFormatTypeIsActive) {
        this.downloadMediaFormatTypeIsActive = downloadMediaFormatTypeIsActive;
    }

}
