package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EventSources generated by hbm2java
 */
@Entity
//@Table(name = "EventSources")

public class EventSources implements java.io.Serializable {

    private short eventSourceId;
    private String eventSourceName;
    private Date eventSourceCreatedDate;
    private boolean eventSourceIsActive;

    public EventSources() {
    }

    public EventSources(short eventSourceId, String eventSourceName, Date eventSourceCreatedDate,
            boolean eventSourceIsActive) {
        this.eventSourceId = eventSourceId;
        this.eventSourceName = eventSourceName;
        this.eventSourceCreatedDate = eventSourceCreatedDate;
        this.eventSourceIsActive = eventSourceIsActive;
    }

    public short getEventSourceId() {
        return this.eventSourceId;
    }

    public void setEventSourceId(short eventSourceId) {
        this.eventSourceId = eventSourceId;
    }

    public String getEventSourceName() {
        return this.eventSourceName;
    }

    public void setEventSourceName(String eventSourceName) {
        this.eventSourceName = eventSourceName;
    }

    public Date getEventSourceCreatedDate() {
        return this.eventSourceCreatedDate;
    }

    public void setEventSourceCreatedDate(Date eventSourceCreatedDate) {
        this.eventSourceCreatedDate = eventSourceCreatedDate;
    }

    public boolean isEventSourceIsActive() {
        return this.eventSourceIsActive;
    }

    public void setEventSourceIsActive(boolean eventSourceIsActive) {
        this.eventSourceIsActive = eventSourceIsActive;
    }

}
