package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EventLog generated by hbm2java
 */
@Entity
//@Table(name = "EventLog")

public class EventLog implements java.io.Serializable {

    private long eventLogId;
    private short eventTypeId;
    private short eventSourceId;
    private String eventMessage;
    private int userId;
    private Date eventDateTime;

    public EventLog() {
    }

    public EventLog(long eventLogId, short eventTypeId, short eventSourceId, String eventMessage, int userId,
            Date eventDateTime) {
        this.eventLogId = eventLogId;
        this.eventTypeId = eventTypeId;
        this.eventSourceId = eventSourceId;
        this.eventMessage = eventMessage;
        this.userId = userId;
        this.eventDateTime = eventDateTime;
    }

    public long getEventLogId() {
        return this.eventLogId;
    }

    public void setEventLogId(long eventLogId) {
        this.eventLogId = eventLogId;
    }

    public short getEventTypeId() {
        return this.eventTypeId;
    }

    public void setEventTypeId(short eventTypeId) {
        this.eventTypeId = eventTypeId;
    }

    public short getEventSourceId() {
        return this.eventSourceId;
    }

    public void setEventSourceId(short eventSourceId) {
        this.eventSourceId = eventSourceId;
    }

    public String getEventMessage() {
        return this.eventMessage;
    }

    public void setEventMessage(String eventMessage) {
        this.eventMessage = eventMessage;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Date getEventDateTime() {
        return this.eventDateTime;
    }

    public void setEventDateTime(Date eventDateTime) {
        this.eventDateTime = eventDateTime;
    }

}
