package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Leagues generated by hbm2java
 */
@Entity
//@Table(name = "Leagues")

public class Leagues implements java.io.Serializable {

    private short leagueId;
    private SportTypes sportTypes;
    private String leagueName;
    private Date leagueCreatedDate;
    private boolean leagueIsActive;
    private Short orderby;

    public Leagues() {
    }

    public Leagues(short leagueId, SportTypes sportTypes, String leagueName, Date leagueCreatedDate,
            boolean leagueIsActive) {
        this.leagueId = leagueId;
        this.sportTypes = sportTypes;
        this.leagueName = leagueName;
        this.leagueCreatedDate = leagueCreatedDate;
        this.leagueIsActive = leagueIsActive;
    }

    public Leagues(short leagueId, SportTypes sportTypes, String leagueName, Date leagueCreatedDate,
            boolean leagueIsActive, Short orderby) {
        this.leagueId = leagueId;
        this.sportTypes = sportTypes;
        this.leagueName = leagueName;
        this.leagueCreatedDate = leagueCreatedDate;
        this.leagueIsActive = leagueIsActive;
        this.orderby = orderby;
    }

    public short getLeagueId() {
        return this.leagueId;
    }

    public void setLeagueId(short leagueId) {
        this.leagueId = leagueId;
    }

    public SportTypes getSportTypes() {
        return this.sportTypes;
    }

    public void setSportTypes(SportTypes sportTypes) {
        this.sportTypes = sportTypes;
    }

    public String getLeagueName() {
        return this.leagueName;
    }

    public void setLeagueName(String leagueName) {
        this.leagueName = leagueName;
    }

    public Date getLeagueCreatedDate() {
        return this.leagueCreatedDate;
    }

    public void setLeagueCreatedDate(Date leagueCreatedDate) {
        this.leagueCreatedDate = leagueCreatedDate;
    }

    public boolean isLeagueIsActive() {
        return this.leagueIsActive;
    }

    public void setLeagueIsActive(boolean leagueIsActive) {
        this.leagueIsActive = leagueIsActive;
    }

    public Short getOrderby() {
        return this.orderby;
    }

    public void setOrderby(Short orderby) {
        this.orderby = orderby;
    }

}
