package com.xosdigital.tcx.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

/**
 * Migration generated by hbm2java
 */
@Entity
//@Table(name = "Migration")
public class Migration implements java.io.Serializable {

    private int tcxAssetId;
    private String vaultAssetId;
    private String vaultResourcePath;
    private String azureBlobPath;
    private String migrationStatus;
    private String resourceMd5;
    private String status;
    private String resourceSha1;

    public Migration() {
    }

    public Migration(int tcxAssetId, String vaultAssetId, String migrationStatus, String status) {
        this.tcxAssetId = tcxAssetId;
        this.vaultAssetId = vaultAssetId;
        this.migrationStatus = migrationStatus;
        this.status = status;
    }

    public Migration(int tcxAssetId, String vaultAssetId, String vaultResourcePath, String azureBlobPath,
            String migrationStatus, String resourceMd5, String status, String resourceSha1) {
        this.tcxAssetId = tcxAssetId;
        this.vaultAssetId = vaultAssetId;
        this.vaultResourcePath = vaultResourcePath;
        this.azureBlobPath = azureBlobPath;
        this.migrationStatus = migrationStatus;
        this.resourceMd5 = resourceMd5;
        this.status = status;
        this.resourceSha1 = resourceSha1;
    }

    public int getTcxAssetId() {
        return this.tcxAssetId;
    }

    public void setTcxAssetId(int tcxAssetId) {
        this.tcxAssetId = tcxAssetId;
    }

    public String getVaultAssetId() {
        return this.vaultAssetId;
    }

    public void setVaultAssetId(String vaultAssetId) {
        this.vaultAssetId = vaultAssetId;
    }

    public String getVaultResourcePath() {
        return this.vaultResourcePath;
    }

    public void setVaultResourcePath(String vaultResourcePath) {
        this.vaultResourcePath = vaultResourcePath;
    }

    public String getAzureBlobPath() {
        return this.azureBlobPath;
    }

    public void setAzureBlobPath(String azureBlobPath) {
        this.azureBlobPath = azureBlobPath;
    }

    public String getMigrationStatus() {
        return this.migrationStatus;
    }

    public void setMigrationStatus(String migrationStatus) {
        this.migrationStatus = migrationStatus;
    }

    public String getResourceMd5() {
        return this.resourceMd5;
    }

    public void setResourceMd5(String resourceMd5) {
        this.resourceMd5 = resourceMd5;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getResourceSha1() {
        return this.resourceSha1;
    }

    public void setResourceSha1(String resourceSha1) {
        this.resourceSha1 = resourceSha1;
    }

}
