package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Organizations generated by hbm2java
 */
@Entity
//@Table(name = "Organizations")

public class Organizations implements java.io.Serializable {

    private int organizationId;
    private String organizationName;
    private String abbreviation;
    private String initials;
    private BigDecimal maxStorageSize;
    private BigDecimal storageCurrentlyAllocated;
    private Date organizationCreatedDate;
    private boolean organizationIsActive;
    private boolean isValidated;

    public Organizations() {
    }

    public Organizations(int organizationId, String organizationName, BigDecimal maxStorageSize,
            BigDecimal storageCurrentlyAllocated, Date organizationCreatedDate, boolean organizationIsActive,
            boolean isValidated) {
        this.organizationId = organizationId;
        this.organizationName = organizationName;
        this.maxStorageSize = maxStorageSize;
        this.storageCurrentlyAllocated = storageCurrentlyAllocated;
        this.organizationCreatedDate = organizationCreatedDate;
        this.organizationIsActive = organizationIsActive;
        this.isValidated = isValidated;
    }

    public Organizations(int organizationId, String organizationName, String abbreviation, String initials,
            BigDecimal maxStorageSize, BigDecimal storageCurrentlyAllocated, Date organizationCreatedDate,
            boolean organizationIsActive, boolean isValidated) {
        this.organizationId = organizationId;
        this.organizationName = organizationName;
        this.abbreviation = abbreviation;
        this.initials = initials;
        this.maxStorageSize = maxStorageSize;
        this.storageCurrentlyAllocated = storageCurrentlyAllocated;
        this.organizationCreatedDate = organizationCreatedDate;
        this.organizationIsActive = organizationIsActive;
        this.isValidated = isValidated;
    }

    public int getOrganizationId() {
        return this.organizationId;
    }

    public void setOrganizationId(int organizationId) {
        this.organizationId = organizationId;
    }

    public String getOrganizationName() {
        return this.organizationName;
    }

    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    public String getAbbreviation() {
        return this.abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getInitials() {
        return this.initials;
    }

    public void setInitials(String initials) {
        this.initials = initials;
    }

    public BigDecimal getMaxStorageSize() {
        return this.maxStorageSize;
    }

    public void setMaxStorageSize(BigDecimal maxStorageSize) {
        this.maxStorageSize = maxStorageSize;
    }

    public BigDecimal getStorageCurrentlyAllocated() {
        return this.storageCurrentlyAllocated;
    }

    public void setStorageCurrentlyAllocated(BigDecimal storageCurrentlyAllocated) {
        this.storageCurrentlyAllocated = storageCurrentlyAllocated;
    }

    public Date getOrganizationCreatedDate() {
        return this.organizationCreatedDate;
    }

    public void setOrganizationCreatedDate(Date organizationCreatedDate) {
        this.organizationCreatedDate = organizationCreatedDate;
    }

    public boolean isOrganizationIsActive() {
        return this.organizationIsActive;
    }

    public void setOrganizationIsActive(boolean organizationIsActive) {
        this.organizationIsActive = organizationIsActive;
    }

    public boolean isIsValidated() {
        return this.isValidated;
    }

    public void setIsValidated(boolean isValidated) {
        this.isValidated = isValidated;
    }

}
