package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SchoolsLookup generated by hbm2java
 */
@Entity
//@Table(name = "SchoolsLookup")

public class SchoolsLookup implements java.io.Serializable {

    private int itemId;
    private Serializable fullName;
    private Serializable abbrName;
    private Serializable shortName;
    private Serializable initials;
    private Serializable nick;
    private Serializable abbrAlias;
    private Serializable primaryHexColor;
    private Integer confId;
    private Serializable conference;
    private Serializable division;
    private Serializable logo50;
    private Serializable logo85;
    private Serializable logo;
    private Serializable altLogo;
    private Serializable city;
    private Serializable state;
    private Serializable zip;
    private Serializable educationalUrl;
    private Serializable athleticsUrl;
    private Serializable homeFbStadium;
    private Serializable menBasketballTeam;
    private Serializable womenBbArena;
    private Serializable homeBaseballField;
    private Serializable homeSoftballField;
    private Serializable homeSoccerField;
    private Serializable homeGolfCourse;
    private Serializable lacrosseField;
    private Serializable fieldHockey;
    private Serializable swimDivCenter;
    private Serializable tennisCourt;
    private Serializable trackField;
    private Serializable volleyball;
    private Serializable crossCountry;
    private Serializable rowing;
    private Serializable websiteProvider;
    private Serializable dataTrack;
    private Serializable schoolKey;
    private Serializable vaultName;
    private Integer nmnSchoolId;
    private Integer statsLlcCollegeId;
    private Integer statsLlcFbglobalId;
    private Integer statsLlcBbglobalId;
    private Integer statsLlcBkglobalId;

    public SchoolsLookup() {
    }

    public SchoolsLookup(int itemId) {
        this.itemId = itemId;
    }

    public SchoolsLookup(int itemId, Serializable fullName, Serializable abbrName, Serializable shortName,
            Serializable initials, Serializable nick, Serializable abbrAlias, Serializable primaryHexColor,
            Integer confId, Serializable conference, Serializable division, Serializable logo50, Serializable logo85,
            Serializable logo, Serializable altLogo, Serializable city, Serializable state, Serializable zip,
            Serializable educationalUrl, Serializable athleticsUrl, Serializable homeFbStadium,
            Serializable menBasketballTeam, Serializable womenBbArena, Serializable homeBaseballField,
            Serializable homeSoftballField, Serializable homeSoccerField, Serializable homeGolfCourse,
            Serializable lacrosseField, Serializable fieldHockey, Serializable swimDivCenter, Serializable tennisCourt,
            Serializable trackField, Serializable volleyball, Serializable crossCountry, Serializable rowing,
            Serializable websiteProvider, Serializable dataTrack, Serializable schoolKey, Serializable vaultName,
            Integer nmnSchoolId, Integer statsLlcCollegeId, Integer statsLlcFbglobalId, Integer statsLlcBbglobalId,
            Integer statsLlcBkglobalId) {
        this.itemId = itemId;
        this.fullName = fullName;
        this.abbrName = abbrName;
        this.shortName = shortName;
        this.initials = initials;
        this.nick = nick;
        this.abbrAlias = abbrAlias;
        this.primaryHexColor = primaryHexColor;
        this.confId = confId;
        this.conference = conference;
        this.division = division;
        this.logo50 = logo50;
        this.logo85 = logo85;
        this.logo = logo;
        this.altLogo = altLogo;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.educationalUrl = educationalUrl;
        this.athleticsUrl = athleticsUrl;
        this.homeFbStadium = homeFbStadium;
        this.menBasketballTeam = menBasketballTeam;
        this.womenBbArena = womenBbArena;
        this.homeBaseballField = homeBaseballField;
        this.homeSoftballField = homeSoftballField;
        this.homeSoccerField = homeSoccerField;
        this.homeGolfCourse = homeGolfCourse;
        this.lacrosseField = lacrosseField;
        this.fieldHockey = fieldHockey;
        this.swimDivCenter = swimDivCenter;
        this.tennisCourt = tennisCourt;
        this.trackField = trackField;
        this.volleyball = volleyball;
        this.crossCountry = crossCountry;
        this.rowing = rowing;
        this.websiteProvider = websiteProvider;
        this.dataTrack = dataTrack;
        this.schoolKey = schoolKey;
        this.vaultName = vaultName;
        this.nmnSchoolId = nmnSchoolId;
        this.statsLlcCollegeId = statsLlcCollegeId;
        this.statsLlcFbglobalId = statsLlcFbglobalId;
        this.statsLlcBbglobalId = statsLlcBbglobalId;
        this.statsLlcBkglobalId = statsLlcBkglobalId;
    }

    public int getItemId() {
        return this.itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public Serializable getFullName() {
        return this.fullName;
    }

    public void setFullName(Serializable fullName) {
        this.fullName = fullName;
    }

    public Serializable getAbbrName() {
        return this.abbrName;
    }

    public void setAbbrName(Serializable abbrName) {
        this.abbrName = abbrName;
    }

    public Serializable getShortName() {
        return this.shortName;
    }

    public void setShortName(Serializable shortName) {
        this.shortName = shortName;
    }

    public Serializable getInitials() {
        return this.initials;
    }

    public void setInitials(Serializable initials) {
        this.initials = initials;
    }

    public Serializable getNick() {
        return this.nick;
    }

    public void setNick(Serializable nick) {
        this.nick = nick;
    }

    public Serializable getAbbrAlias() {
        return this.abbrAlias;
    }

    public void setAbbrAlias(Serializable abbrAlias) {
        this.abbrAlias = abbrAlias;
    }

    public Serializable getPrimaryHexColor() {
        return this.primaryHexColor;
    }

    public void setPrimaryHexColor(Serializable primaryHexColor) {
        this.primaryHexColor = primaryHexColor;
    }

    public Integer getConfId() {
        return this.confId;
    }

    public void setConfId(Integer confId) {
        this.confId = confId;
    }

    public Serializable getConference() {
        return this.conference;
    }

    public void setConference(Serializable conference) {
        this.conference = conference;
    }

    public Serializable getDivision() {
        return this.division;
    }

    public void setDivision(Serializable division) {
        this.division = division;
    }

    public Serializable getLogo50() {
        return this.logo50;
    }

    public void setLogo50(Serializable logo50) {
        this.logo50 = logo50;
    }

    public Serializable getLogo85() {
        return this.logo85;
    }

    public void setLogo85(Serializable logo85) {
        this.logo85 = logo85;
    }

    public Serializable getLogo() {
        return this.logo;
    }

    public void setLogo(Serializable logo) {
        this.logo = logo;
    }

    public Serializable getAltLogo() {
        return this.altLogo;
    }

    public void setAltLogo(Serializable altLogo) {
        this.altLogo = altLogo;
    }

    public Serializable getCity() {
        return this.city;
    }

    public void setCity(Serializable city) {
        this.city = city;
    }

    public Serializable getState() {
        return this.state;
    }

    public void setState(Serializable state) {
        this.state = state;
    }

    public Serializable getZip() {
        return this.zip;
    }

    public void setZip(Serializable zip) {
        this.zip = zip;
    }

    public Serializable getEducationalUrl() {
        return this.educationalUrl;
    }

    public void setEducationalUrl(Serializable educationalUrl) {
        this.educationalUrl = educationalUrl;
    }

    public Serializable getAthleticsUrl() {
        return this.athleticsUrl;
    }

    public void setAthleticsUrl(Serializable athleticsUrl) {
        this.athleticsUrl = athleticsUrl;
    }

    public Serializable getHomeFbStadium() {
        return this.homeFbStadium;
    }

    public void setHomeFbStadium(Serializable homeFbStadium) {
        this.homeFbStadium = homeFbStadium;
    }

    public Serializable getMenBasketballTeam() {
        return this.menBasketballTeam;
    }

    public void setMenBasketballTeam(Serializable menBasketballTeam) {
        this.menBasketballTeam = menBasketballTeam;
    }

    public Serializable getWomenBbArena() {
        return this.womenBbArena;
    }

    public void setWomenBbArena(Serializable womenBbArena) {
        this.womenBbArena = womenBbArena;
    }

    public Serializable getHomeBaseballField() {
        return this.homeBaseballField;
    }

    public void setHomeBaseballField(Serializable homeBaseballField) {
        this.homeBaseballField = homeBaseballField;
    }

    public Serializable getHomeSoftballField() {
        return this.homeSoftballField;
    }

    public void setHomeSoftballField(Serializable homeSoftballField) {
        this.homeSoftballField = homeSoftballField;
    }

    public Serializable getHomeSoccerField() {
        return this.homeSoccerField;
    }

    public void setHomeSoccerField(Serializable homeSoccerField) {
        this.homeSoccerField = homeSoccerField;
    }

    public Serializable getHomeGolfCourse() {
        return this.homeGolfCourse;
    }

    public void setHomeGolfCourse(Serializable homeGolfCourse) {
        this.homeGolfCourse = homeGolfCourse;
    }

    public Serializable getLacrosseField() {
        return this.lacrosseField;
    }

    public void setLacrosseField(Serializable lacrosseField) {
        this.lacrosseField = lacrosseField;
    }

    public Serializable getFieldHockey() {
        return this.fieldHockey;
    }

    public void setFieldHockey(Serializable fieldHockey) {
        this.fieldHockey = fieldHockey;
    }

    public Serializable getSwimDivCenter() {
        return this.swimDivCenter;
    }

    public void setSwimDivCenter(Serializable swimDivCenter) {
        this.swimDivCenter = swimDivCenter;
    }

    public Serializable getTennisCourt() {
        return this.tennisCourt;
    }

    public void setTennisCourt(Serializable tennisCourt) {
        this.tennisCourt = tennisCourt;
    }

    public Serializable getTrackField() {
        return this.trackField;
    }

    public void setTrackField(Serializable trackField) {
        this.trackField = trackField;
    }

    public Serializable getVolleyball() {
        return this.volleyball;
    }

    public void setVolleyball(Serializable volleyball) {
        this.volleyball = volleyball;
    }

    public Serializable getCrossCountry() {
        return this.crossCountry;
    }

    public void setCrossCountry(Serializable crossCountry) {
        this.crossCountry = crossCountry;
    }

    public Serializable getRowing() {
        return this.rowing;
    }

    public void setRowing(Serializable rowing) {
        this.rowing = rowing;
    }

    public Serializable getWebsiteProvider() {
        return this.websiteProvider;
    }

    public void setWebsiteProvider(Serializable websiteProvider) {
        this.websiteProvider = websiteProvider;
    }

    public Serializable getDataTrack() {
        return this.dataTrack;
    }

    public void setDataTrack(Serializable dataTrack) {
        this.dataTrack = dataTrack;
    }

    public Serializable getSchoolKey() {
        return this.schoolKey;
    }

    public void setSchoolKey(Serializable schoolKey) {
        this.schoolKey = schoolKey;
    }

    public Serializable getVaultName() {
        return this.vaultName;
    }

    public void setVaultName(Serializable vaultName) {
        this.vaultName = vaultName;
    }

    public Integer getNmnSchoolId() {
        return this.nmnSchoolId;
    }

    public void setNmnSchoolId(Integer nmnSchoolId) {
        this.nmnSchoolId = nmnSchoolId;
    }

    public Integer getStatsLlcCollegeId() {
        return this.statsLlcCollegeId;
    }

    public void setStatsLlcCollegeId(Integer statsLlcCollegeId) {
        this.statsLlcCollegeId = statsLlcCollegeId;
    }

    public Integer getStatsLlcFbglobalId() {
        return this.statsLlcFbglobalId;
    }

    public void setStatsLlcFbglobalId(Integer statsLlcFbglobalId) {
        this.statsLlcFbglobalId = statsLlcFbglobalId;
    }

    public Integer getStatsLlcBbglobalId() {
        return this.statsLlcBbglobalId;
    }

    public void setStatsLlcBbglobalId(Integer statsLlcBbglobalId) {
        this.statsLlcBbglobalId = statsLlcBbglobalId;
    }

    public Integer getStatsLlcBkglobalId() {
        return this.statsLlcBkglobalId;
    }

    public void setStatsLlcBkglobalId(Integer statsLlcBkglobalId) {
        this.statsLlcBkglobalId = statsLlcBkglobalId;
    }

}
