package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SportTeamsSportTeamGroups generated by hbm2java
 */
@Entity
@Table(name = "SportTeams_SportTeamGroups")

public class SportTeamsSportTeamGroups implements java.io.Serializable {

    private int sportTeamsSportTeamGroupsId;
    private SportTeamGroups sportTeamGroups;
    private SportTeams sportTeams;
    private Date sportTeamSportTeamGroupCreatedDate;
    private boolean sportTeamSportTeamGroupIsActive;

    public SportTeamsSportTeamGroups() {
    }

    public SportTeamsSportTeamGroups(int sportTeamsSportTeamGroupsId, SportTeamGroups sportTeamGroups,
            SportTeams sportTeams, Date sportTeamSportTeamGroupCreatedDate, boolean sportTeamSportTeamGroupIsActive) {
        this.sportTeamsSportTeamGroupsId = sportTeamsSportTeamGroupsId;
        this.sportTeamGroups = sportTeamGroups;
        this.sportTeams = sportTeams;
        this.sportTeamSportTeamGroupCreatedDate = sportTeamSportTeamGroupCreatedDate;
        this.sportTeamSportTeamGroupIsActive = sportTeamSportTeamGroupIsActive;
    }

    public int getSportTeamsSportTeamGroupsId() {
        return this.sportTeamsSportTeamGroupsId;
    }

    public void setSportTeamsSportTeamGroupsId(int sportTeamsSportTeamGroupsId) {
        this.sportTeamsSportTeamGroupsId = sportTeamsSportTeamGroupsId;
    }

    public SportTeamGroups getSportTeamGroups() {
        return this.sportTeamGroups;
    }

    public void setSportTeamGroups(SportTeamGroups sportTeamGroups) {
        this.sportTeamGroups = sportTeamGroups;
    }

    public SportTeams getSportTeams() {
        return this.sportTeams;
    }

    public void setSportTeams(SportTeams sportTeams) {
        this.sportTeams = sportTeams;
    }

    public Date getSportTeamSportTeamGroupCreatedDate() {
        return this.sportTeamSportTeamGroupCreatedDate;
    }

    public void setSportTeamSportTeamGroupCreatedDate(Date sportTeamSportTeamGroupCreatedDate) {
        this.sportTeamSportTeamGroupCreatedDate = sportTeamSportTeamGroupCreatedDate;
    }

    public boolean isSportTeamSportTeamGroupIsActive() {
        return this.sportTeamSportTeamGroupIsActive;
    }

    public void setSportTeamSportTeamGroupIsActive(boolean sportTeamSportTeamGroupIsActive) {
        this.sportTeamSportTeamGroupIsActive = sportTeamSportTeamGroupIsActive;
    }

}
