package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SportTeamGroups generated by hbm2java
 */
@Entity
//@Table(name = "SportTeamGroups")

public class SportTeamGroups implements java.io.Serializable {

    private int sportTeamGroupId;
    private SportTypes sportTypes;
    private String sportTeamGroupName;
    private short leagueId;
    private Date sportTeamGroupCreatedDate;
    private boolean sportTeamGroupIsActive;
    private Integer sportTeamOwnerId;
    private Set sportTeamsSportTeamGroupses = new HashSet(0);

    public SportTeamGroups() {
    }

    public SportTeamGroups(int sportTeamGroupId, SportTypes sportTypes, String sportTeamGroupName, short leagueId,
            Date sportTeamGroupCreatedDate, boolean sportTeamGroupIsActive) {
        this.sportTeamGroupId = sportTeamGroupId;
        this.sportTypes = sportTypes;
        this.sportTeamGroupName = sportTeamGroupName;
        this.leagueId = leagueId;
        this.sportTeamGroupCreatedDate = sportTeamGroupCreatedDate;
        this.sportTeamGroupIsActive = sportTeamGroupIsActive;
    }

    public SportTeamGroups(int sportTeamGroupId, SportTypes sportTypes, String sportTeamGroupName, short leagueId,
            Date sportTeamGroupCreatedDate, boolean sportTeamGroupIsActive, Integer sportTeamOwnerId,
            Set sportTeamsSportTeamGroupses) {
        this.sportTeamGroupId = sportTeamGroupId;
        this.sportTypes = sportTypes;
        this.sportTeamGroupName = sportTeamGroupName;
        this.leagueId = leagueId;
        this.sportTeamGroupCreatedDate = sportTeamGroupCreatedDate;
        this.sportTeamGroupIsActive = sportTeamGroupIsActive;
        this.sportTeamOwnerId = sportTeamOwnerId;
        this.sportTeamsSportTeamGroupses = sportTeamsSportTeamGroupses;
    }

    public int getSportTeamGroupId() {
        return this.sportTeamGroupId;
    }

    public void setSportTeamGroupId(int sportTeamGroupId) {
        this.sportTeamGroupId = sportTeamGroupId;
    }

    public SportTypes getSportTypes() {
        return this.sportTypes;
    }

    public void setSportTypes(SportTypes sportTypes) {
        this.sportTypes = sportTypes;
    }

    public String getSportTeamGroupName() {
        return this.sportTeamGroupName;
    }

    public void setSportTeamGroupName(String sportTeamGroupName) {
        this.sportTeamGroupName = sportTeamGroupName;
    }

    public short getLeagueId() {
        return this.leagueId;
    }

    public void setLeagueId(short leagueId) {
        this.leagueId = leagueId;
    }

    public Date getSportTeamGroupCreatedDate() {
        return this.sportTeamGroupCreatedDate;
    }

    public void setSportTeamGroupCreatedDate(Date sportTeamGroupCreatedDate) {
        this.sportTeamGroupCreatedDate = sportTeamGroupCreatedDate;
    }

    public boolean isSportTeamGroupIsActive() {
        return this.sportTeamGroupIsActive;
    }

    public void setSportTeamGroupIsActive(boolean sportTeamGroupIsActive) {
        this.sportTeamGroupIsActive = sportTeamGroupIsActive;
    }

    public Integer getSportTeamOwnerId() {
        return this.sportTeamOwnerId;
    }

    public void setSportTeamOwnerId(Integer sportTeamOwnerId) {
        this.sportTeamOwnerId = sportTeamOwnerId;
    }

    public Set getSportTeamsSportTeamGroupses() {
        return this.sportTeamsSportTeamGroupses;
    }

    public void setSportTeamsSportTeamGroupses(Set sportTeamsSportTeamGroupses) {
        this.sportTeamsSportTeamGroupses = sportTeamsSportTeamGroupses;
    }

}
