package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SportTeams generated by hbm2java
 */
@Entity
//@Table(name = "SportTeams")

public class SportTeams implements java.io.Serializable {

    private int sportTeamId;
    private String sportTeamName;
    private int organizationId;
    private short sportTypeId;
    private Date sportTeamCreatedDate;
    private boolean sportTeamIsActive;
    private Set usersSportTeamses = new HashSet(0);
    private Set assetSportTeamOwnershipLogs = new HashSet(0);
    private Set assetsSportTeamses = new HashSet(0);
    private Set sportTeamsSportTeamGroupses = new HashSet(0);

    public SportTeams() {
    }

    public SportTeams(int sportTeamId, String sportTeamName, int organizationId, short sportTypeId,
            Date sportTeamCreatedDate, boolean sportTeamIsActive) {
        this.sportTeamId = sportTeamId;
        this.sportTeamName = sportTeamName;
        this.organizationId = organizationId;
        this.sportTypeId = sportTypeId;
        this.sportTeamCreatedDate = sportTeamCreatedDate;
        this.sportTeamIsActive = sportTeamIsActive;
    }

    public SportTeams(int sportTeamId, String sportTeamName, int organizationId, short sportTypeId,
            Date sportTeamCreatedDate, boolean sportTeamIsActive, Set usersSportTeamses,
            Set assetSportTeamOwnershipLogs, Set assetsSportTeamses, Set sportTeamsSportTeamGroupses) {
        this.sportTeamId = sportTeamId;
        this.sportTeamName = sportTeamName;
        this.organizationId = organizationId;
        this.sportTypeId = sportTypeId;
        this.sportTeamCreatedDate = sportTeamCreatedDate;
        this.sportTeamIsActive = sportTeamIsActive;
        this.usersSportTeamses = usersSportTeamses;
        this.assetSportTeamOwnershipLogs = assetSportTeamOwnershipLogs;
        this.assetsSportTeamses = assetsSportTeamses;
        this.sportTeamsSportTeamGroupses = sportTeamsSportTeamGroupses;
    }

    public int getSportTeamId() {
        return this.sportTeamId;
    }

    public void setSportTeamId(int sportTeamId) {
        this.sportTeamId = sportTeamId;
    }

    public String getSportTeamName() {
        return this.sportTeamName;
    }

    public void setSportTeamName(String sportTeamName) {
        this.sportTeamName = sportTeamName;
    }

    public int getOrganizationId() {
        return this.organizationId;
    }

    public void setOrganizationId(int organizationId) {
        this.organizationId = organizationId;
    }

    public short getSportTypeId() {
        return this.sportTypeId;
    }

    public void setSportTypeId(short sportTypeId) {
        this.sportTypeId = sportTypeId;
    }

    public Date getSportTeamCreatedDate() {
        return this.sportTeamCreatedDate;
    }

    public void setSportTeamCreatedDate(Date sportTeamCreatedDate) {
        this.sportTeamCreatedDate = sportTeamCreatedDate;
    }

    public boolean isSportTeamIsActive() {
        return this.sportTeamIsActive;
    }

    public void setSportTeamIsActive(boolean sportTeamIsActive) {
        this.sportTeamIsActive = sportTeamIsActive;
    }

    public Set getUsersSportTeamses() {
        return this.usersSportTeamses;
    }

    public void setUsersSportTeamses(Set usersSportTeamses) {
        this.usersSportTeamses = usersSportTeamses;
    }

    public Set getAssetSportTeamOwnershipLogs() {
        return this.assetSportTeamOwnershipLogs;
    }

    public void setAssetSportTeamOwnershipLogs(Set assetSportTeamOwnershipLogs) {
        this.assetSportTeamOwnershipLogs = assetSportTeamOwnershipLogs;
    }

    public Set getAssetsSportTeamses() {
        return this.assetsSportTeamses;
    }

    public void setAssetsSportTeamses(Set assetsSportTeamses) {
        this.assetsSportTeamses = assetsSportTeamses;
    }

    public Set getSportTeamsSportTeamGroupses() {
        return this.sportTeamsSportTeamGroupses;
    }

    public void setSportTeamsSportTeamGroupses(Set sportTeamsSportTeamGroupses) {
        this.sportTeamsSportTeamGroupses = sportTeamsSportTeamGroupses;
    }

}
