package com.xosdigital.tcx.domain;

import javax.persistence.Entity;
import javax.persistence.Table;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

/**
 * UsersDownloadPreferences generated by hbm2java
 */
@Entity
@Table(name = "Users_DownloadPreferences")

public class UsersDownloadPreferences implements java.io.Serializable {

    private int userDownloadPrefrenceId;
    private int userId;
    private short downloadMediaFormatTypeId;
    private short downloadMetaDataFormatTypeId;

    public UsersDownloadPreferences() {
    }

    public UsersDownloadPreferences(int userDownloadPrefrenceId, int userId, short downloadMediaFormatTypeId,
            short downloadMetaDataFormatTypeId) {
        this.userDownloadPrefrenceId = userDownloadPrefrenceId;
        this.userId = userId;
        this.downloadMediaFormatTypeId = downloadMediaFormatTypeId;
        this.downloadMetaDataFormatTypeId = downloadMetaDataFormatTypeId;
    }

    public int getUserDownloadPrefrenceId() {
        return this.userDownloadPrefrenceId;
    }

    public void setUserDownloadPrefrenceId(int userDownloadPrefrenceId) {
        this.userDownloadPrefrenceId = userDownloadPrefrenceId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public short getDownloadMediaFormatTypeId() {
        return this.downloadMediaFormatTypeId;
    }

    public void setDownloadMediaFormatTypeId(short downloadMediaFormatTypeId) {
        this.downloadMediaFormatTypeId = downloadMediaFormatTypeId;
    }

    public short getDownloadMetaDataFormatTypeId() {
        return this.downloadMetaDataFormatTypeId;
    }

    public void setDownloadMetaDataFormatTypeId(short downloadMetaDataFormatTypeId) {
        this.downloadMetaDataFormatTypeId = downloadMetaDataFormatTypeId;
    }

}
