package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsersSportTeams generated by hbm2java
 */
@Entity
@Table(name = "Users_SportTeams")

public class UsersSportTeams implements java.io.Serializable {

    private int usersSportTeamsId;
    private Users users;
    private UserSportTeamPermissions userSportTeamPermissions;
    private SportTeams sportTeams;
    private Date userSportTeamCreatedDate;
    private boolean userSportTeamIsActive;

    public UsersSportTeams() {
    }

    public UsersSportTeams(int usersSportTeamsId, Users users, UserSportTeamPermissions userSportTeamPermissions,
            SportTeams sportTeams, Date userSportTeamCreatedDate, boolean userSportTeamIsActive) {
        this.usersSportTeamsId = usersSportTeamsId;
        this.users = users;
        this.userSportTeamPermissions = userSportTeamPermissions;
        this.sportTeams = sportTeams;
        this.userSportTeamCreatedDate = userSportTeamCreatedDate;
        this.userSportTeamIsActive = userSportTeamIsActive;
    }

    public int getUsersSportTeamsId() {
        return this.usersSportTeamsId;
    }

    public void setUsersSportTeamsId(int usersSportTeamsId) {
        this.usersSportTeamsId = usersSportTeamsId;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public UserSportTeamPermissions getUserSportTeamPermissions() {
        return this.userSportTeamPermissions;
    }

    public void setUserSportTeamPermissions(UserSportTeamPermissions userSportTeamPermissions) {
        this.userSportTeamPermissions = userSportTeamPermissions;
    }

    public SportTeams getSportTeams() {
        return this.sportTeams;
    }

    public void setSportTeams(SportTeams sportTeams) {
        this.sportTeams = sportTeams;
    }

    public Date getUserSportTeamCreatedDate() {
        return this.userSportTeamCreatedDate;
    }

    public void setUserSportTeamCreatedDate(Date userSportTeamCreatedDate) {
        this.userSportTeamCreatedDate = userSportTeamCreatedDate;
    }

    public boolean isUserSportTeamIsActive() {
        return this.userSportTeamIsActive;
    }

    public void setUserSportTeamIsActive(boolean userSportTeamIsActive) {
        this.userSportTeamIsActive = userSportTeamIsActive;
    }

}
