package com.xosdigital.tcx.domain;

// Generated Jan 9, 2014 5:19:54 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
//@Table(name = "Users")

public class Users implements java.io.Serializable {

    private int userId;
    private String password;
    private String firstName;
    private String lastName;
    private String emailAddress;
    private String cellPhone;
    private String mobileCarrier;
    private boolean resetPasswordOnNextLogin;
    private boolean isSiteAdministrator;
    private boolean isGlobalUserAdministrator;
    private boolean isTeamUserAdministrator;
    private Date userCreatedDate;
    private boolean userIsActive;
    private Set userSettingses = new HashSet(0);
    private Set usersSportTeamses = new HashSet(0);
    private Set assetsSportTeamses = new HashSet(0);

    public Users() {
    }

    public Users(int userId, String password, String firstName, String lastName, String emailAddress,
            boolean resetPasswordOnNextLogin, boolean isSiteAdministrator, boolean isGlobalUserAdministrator,
            boolean isTeamUserAdministrator, Date userCreatedDate, boolean userIsActive) {
        this.userId = userId;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddress = emailAddress;
        this.resetPasswordOnNextLogin = resetPasswordOnNextLogin;
        this.isSiteAdministrator = isSiteAdministrator;
        this.isGlobalUserAdministrator = isGlobalUserAdministrator;
        this.isTeamUserAdministrator = isTeamUserAdministrator;
        this.userCreatedDate = userCreatedDate;
        this.userIsActive = userIsActive;
    }

    public Users(int userId, String password, String firstName, String lastName, String emailAddress, String cellPhone,
            String mobileCarrier, boolean resetPasswordOnNextLogin, boolean isSiteAdministrator,
            boolean isGlobalUserAdministrator, boolean isTeamUserAdministrator, Date userCreatedDate,
            boolean userIsActive, Set userSettingses, Set usersSportTeamses, Set assetsSportTeamses) {
        this.userId = userId;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddress = emailAddress;
        this.cellPhone = cellPhone;
        this.mobileCarrier = mobileCarrier;
        this.resetPasswordOnNextLogin = resetPasswordOnNextLogin;
        this.isSiteAdministrator = isSiteAdministrator;
        this.isGlobalUserAdministrator = isGlobalUserAdministrator;
        this.isTeamUserAdministrator = isTeamUserAdministrator;
        this.userCreatedDate = userCreatedDate;
        this.userIsActive = userIsActive;
        this.userSettingses = userSettingses;
        this.usersSportTeamses = usersSportTeamses;
        this.assetsSportTeamses = assetsSportTeamses;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getCellPhone() {
        return this.cellPhone;
    }

    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    public String getMobileCarrier() {
        return this.mobileCarrier;
    }

    public void setMobileCarrier(String mobileCarrier) {
        this.mobileCarrier = mobileCarrier;
    }

    public boolean isResetPasswordOnNextLogin() {
        return this.resetPasswordOnNextLogin;
    }

    public void setResetPasswordOnNextLogin(boolean resetPasswordOnNextLogin) {
        this.resetPasswordOnNextLogin = resetPasswordOnNextLogin;
    }

    public boolean isIsSiteAdministrator() {
        return this.isSiteAdministrator;
    }

    public void setIsSiteAdministrator(boolean isSiteAdministrator) {
        this.isSiteAdministrator = isSiteAdministrator;
    }

    public boolean isIsGlobalUserAdministrator() {
        return this.isGlobalUserAdministrator;
    }

    public void setIsGlobalUserAdministrator(boolean isGlobalUserAdministrator) {
        this.isGlobalUserAdministrator = isGlobalUserAdministrator;
    }

    public boolean isIsTeamUserAdministrator() {
        return this.isTeamUserAdministrator;
    }

    public void setIsTeamUserAdministrator(boolean isTeamUserAdministrator) {
        this.isTeamUserAdministrator = isTeamUserAdministrator;
    }

    public Date getUserCreatedDate() {
        return this.userCreatedDate;
    }

    public void setUserCreatedDate(Date userCreatedDate) {
        this.userCreatedDate = userCreatedDate;
    }

    public boolean isUserIsActive() {
        return this.userIsActive;
    }

    public void setUserIsActive(boolean userIsActive) {
        this.userIsActive = userIsActive;
    }

    public Set getUserSettingses() {
        return this.userSettingses;
    }

    public void setUserSettingses(Set userSettingses) {
        this.userSettingses = userSettingses;
    }

    public Set getUsersSportTeamses() {
        return this.usersSportTeamses;
    }

    public void setUsersSportTeamses(Set usersSportTeamses) {
        this.usersSportTeamses = usersSportTeamses;
    }

    public Set getAssetsSportTeamses() {
        return this.assetsSportTeamses;
    }

    public void setAssetsSportTeamses(Set assetsSportTeamses) {
        this.assetsSportTeamses = assetsSportTeamses;
    }

}
